config/routes.rb
Rails.application.routes.draw do

  root "videos#index"

  #resources :videos --> replaces all the below

  #resources :videos, only: [:index, :new, :create, :edit, :update]

  get "/videos" => "videos#index"
  get "/videos/new" => "videos#new"
  post "/videos" => "videos#create"
  get "/videos/:id" => "videos#show", as: :video
  get "/videos/:id/edit" => "videos#edit", as: :edit_video
  patch "/videos/:id" =>  "videos#update"
  delete "/videos/:id" => "videos#destroy"
end

app/models/video.rb
class Video < ActiveRecord::Base

  validates :embed_url, uniqueness: true, presence: true
  validates :title, presence: true

  def youtube_link
    "https://youtu.be/#{self.embed_url}"
  end

  def embed
    '<iframe width="560" height="315" src="https://www.youtube.com/embed/' +
    self.embed_url +
     '" frameborder="0" allowfullscreen></iframe>'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create

    @video = Video.new(self.video_params_create)

    #binding.pry

    if @video.save
    redirect_to videos_path

    else
      render :new
        end
    end

    def show
      @video = Video.find(params[:id])
    end

    def edit
      @video = Video.find(params[:id])
    end

    def update
    @video = Video.find(params[:id])
    if @video.update_attributes(params.require(:video).permit(:embed_url, :title, :album, :featured_artists, :released_on, :tags))
      redirect_to videos_path
    else
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_path
  end

    def video_params_create
      params.require(:video).permit(:title, :embed_url, :released_on, :featured_artists)
    end

    #def video_params_update
     # params.permit.permit(:tags)
    #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MrworldwideTvApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<h1><%= link_to "Mr. Worldwide TV", videos_path %></h1>
<h3>Dale!</h3>

<nav>
  <%= link_to "Add Video", videos_new_path %>
</nav>

</header><!-- /header -->

<%= yield %>

</body>
</html>

app/views/videos/_form.html.erb
<%= form_for @video do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title%>
  <br>
  <%= f.label :released_on %>
  <%= f.date_select :released_on %>
  <br>
  <%= f.label :embed_url, "Youtube Id" %>
  <%= f.text_field :embed_url%>
  <br>
  <%= f.label :tags %>
  <%= f.text_field :tags %>

  <%= f.submit "Edit!" %>
  <% end %>

<ul>

  <% @video.errors.full_messages.each do |message|%>
   <li> <%= message%></li>
  <% end %>
</ul>

app/views/videos/edit.html.erb
<%= render "form" %>

app/views/videos/index.html.erb
<main>
<% @videos.order("created_at desc").each do |video| %>
  <article>
   <h4><%= link_to video.title, video.youtube_link %></h4>

   <div class= embed_div>
   <%=raw video.embed %>
  </div>
   <ul>
     <li> <%= link_to "View video", video_path(video)%></li>
     <li>  <%= link_to "Edit Video", "/videos/#{video.id}/edit" %></li>
     <li>  <%= link_to "Delete this video", "/videos/#{video.id}", method: :delete, data: { confirm:
      "Are you sure you want to delete this video?"} %></li>
   </ul>
  </article>
  <% end %>
</main>

app/views/videos/new.html.erb
<%= render "form" %>

app/views/videos/show.html.erb
<%= Video.name%>

<main>

  <article>
   <h4><%= link_to @video.title, @video.youtube_link %></h4>
   <%= raw @video.embed %>
  </article>

</main>